// @ts-nocheck
// This file contains legacy sample data for development/demo purposes.
// Types don't match current schema - using ts-nocheck to suppress errors.

import type { Goal, Task, JournalEntry, TrainingSession, Meal, Recipe, ShoppingItem, ShoppingList } from "./types"

const today = new Date()
const formatDate = (date: Date) => date.toISOString().split("T")[0]

export const sampleGoals: Goal[] = [
  {
    id: "g1",
    title: "Train Muay Thai 4x per week consistently",
    aspect: "fitness",
    level: "yearly",
    successCriteria: "Complete 200+ training sessions by year end",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progress: 3,
  },
  {
    id: "g2",
    title: "January: Build training habit",
    aspect: "fitness",
    level: "monthly",
    successCriteria: "16 sessions in January",
    startDate: "2026-01-01",
    endDate: "2026-01-31",
    parentId: "g1",
    progress: 12,
  },
  {
    id: "g3",
    title: "Cook 80% of meals at home",
    aspect: "nutrition",
    level: "yearly",
    successCriteria: "Track meals daily and maintain 80% home-cooked ratio",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progress: 15,
  },
  {
    id: "g4",
    title: "Secure senior developer position",
    aspect: "career",
    level: "yearly",
    successCriteria: "Get promoted or land new senior role by Q3",
    startDate: "2026-01-01",
    endDate: "2026-09-30",
    progress: 5,
  },
  {
    id: "g5",
    title: "Build portfolio website",
    aspect: "career",
    level: "monthly",
    successCriteria: "Launch personal portfolio by end of January",
    startDate: "2026-01-01",
    endDate: "2026-01-31",
    parentId: "g4",
    progress: 40,
  },
  {
    id: "g6",
    title: "Save $10,000 emergency fund",
    aspect: "financial",
    level: "yearly",
    successCriteria: "Reach $10,000 in savings account",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progress: 8,
  },
  {
    id: "g7",
    title: "Launch side project MVP",
    aspect: "side-projects",
    level: "yearly",
    successCriteria: "Ship working MVP with 100 users",
    startDate: "2026-01-01",
    endDate: "2026-06-30",
    progress: 20,
  },
  {
    id: "g8",
    title: "Maintain clean living space",
    aspect: "chores",
    level: "yearly",
    successCriteria: "Complete weekly cleaning routine 80% of weeks",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progress: 25,
  },
]

const getDateOffset = (days: number) => {
  const date = new Date(today)
  date.setDate(date.getDate() + days)
  return formatDate(date)
}

export const sampleTasks: Task[] = [
  {
    id: "t1",
    title: "Morning Muay Thai training",
    aspect: "fitness",
    timePreference: "morning",
    durationEstimate: 90,
    status: "pending",
    scheduledDate: getDateOffset(0),
    weeklyGoalId: "g1",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t2",
    title: "Meal prep for the week",
    aspect: "nutrition",
    timePreference: "afternoon",
    durationEstimate: 120,
    status: "pending",
    scheduledDate: getDateOffset(0),
    weeklyGoalId: "g3",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t3",
    title: "Review job applications",
    aspect: "career",
    timePreference: "evening",
    durationEstimate: 30,
    status: "pending",
    scheduledDate: getDateOffset(0),
    weeklyGoalId: "g4",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t4",
    title: "Update portfolio projects page",
    aspect: "career",
    timePreference: "anytime",
    durationEstimate: 60,
    status: "pending",
    scheduledDate: getDateOffset(0),
    weeklyGoalId: "g5",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t5",
    title: "Budget review",
    aspect: "financial",
    timePreference: "evening",
    durationEstimate: 20,
    status: "done",
    scheduledDate: getDateOffset(-1),
    weeklyGoalId: "g6",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t6",
    title: "Work on side project API",
    aspect: "side-projects",
    timePreference: "evening",
    durationEstimate: 90,
    status: "pending",
    scheduledDate: getDateOffset(1),
    weeklyGoalId: "g7",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t7",
    title: "Vacuum and mop floors",
    aspect: "chores",
    timePreference: "morning",
    durationEstimate: 45,
    status: "pending",
    scheduledDate: getDateOffset(1),
    weeklyGoalId: "g8",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t8",
    title: "Cardio session",
    aspect: "fitness",
    timePreference: "morning",
    durationEstimate: 30,
    status: "done",
    scheduledDate: getDateOffset(-2),
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t9",
    title: "Plan weekly meals",
    aspect: "nutrition",
    timePreference: "anytime",
    durationEstimate: 20,
    status: "done",
    scheduledDate: getDateOffset(-3),
    weeklyGoalId: "g3",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "t10",
    title: "Laundry",
    aspect: "chores",
    timePreference: "afternoon",
    durationEstimate: 30,
    status: "skipped",
    scheduledDate: getDateOffset(-4),
    createdAt: today,
    updatedAt: today,
  },
]

export const sampleJournalEntries: JournalEntry[] = [
  {
    id: "j1",
    timestamp: new Date(getDateOffset(0)),
    content:
      "Great training session today! Felt strong and focused. Coach complimented my technique. Excited to keep this momentum going.",
    sentimentScore: 0.8,
    detectedAspects: ["fitness"],
    goalAlignment: "positive",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "j2",
    timestamp: new Date(getDateOffset(-1)),
    content:
      "Had a tough day at work. The project deadline is stressing me out. Need to organize my time better and maybe ask for help.",
    sentimentScore: -0.5,
    detectedAspects: ["career"],
    goalAlignment: "negative",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "j3",
    timestamp: new Date(getDateOffset(-2)),
    content:
      "Cooked a new recipe today - chicken stir fry with lots of veggies. Turned out amazing! Meal prepping is really paying off.",
    sentimentScore: 0.7,
    detectedAspects: ["nutrition"],
    goalAlignment: "positive",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "j4",
    timestamp: new Date(getDateOffset(-5)),
    content:
      "Made good progress on the side project this weekend. The authentication flow is finally working. Feels good to ship features.",
    sentimentScore: 0.6,
    detectedAspects: ["side-projects"],
    goalAlignment: "positive",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "j5",
    timestamp: new Date(getDateOffset(-7)),
    content:
      "Feeling a bit burnt out. Juggling work, training, and side projects is exhausting. Maybe I need to cut back somewhere.",
    sentimentScore: -0.2,
    detectedAspects: ["fitness", "career", "side-projects"],
    goalAlignment: "drift",
    createdAt: today,
    updatedAt: today,
  },
]

export const sampleTrainingSessions: TrainingSession[] = [
  {
    id: "ts1",
    date: getDateOffset(0),
    type: "muay-thai",
    duration: 90,
    intensity: 8,
    notes: "Sparring day - good rounds",
    createdAt: today,
  },
  { id: "ts2", date: getDateOffset(-2), type: "muay-thai", duration: 90, intensity: 7, createdAt: today },
  { id: "ts3", date: getDateOffset(-3), type: "cardio", duration: 30, intensity: 6, notes: "Morning run", createdAt: today },
  { id: "ts4", date: getDateOffset(-5), type: "muay-thai", duration: 90, intensity: 9, notes: "Pad work with coach", createdAt: today },
  { id: "ts5", date: getDateOffset(-7), type: "strength", duration: 60, intensity: 7, notes: "Upper body day", createdAt: today },
  { id: "ts6", date: getDateOffset(-9), type: "muay-thai", duration: 90, intensity: 8, createdAt: today },
  { id: "ts7", date: getDateOffset(-10), type: "flexibility", duration: 45, intensity: 5, notes: "Yoga session", createdAt: today },
  { id: "ts8", date: getDateOffset(-12), type: "muay-thai", duration: 90, intensity: 8, createdAt: today },
]

export const sampleMeals: Meal[] = [
  {
    id: "m1",
    date: getDateOffset(0),
    type: "breakfast",
    description: "Oatmeal with berries and protein powder",
    cooked: true,
    createdAt: today,
  },
  {
    id: "m2",
    date: getDateOffset(0),
    type: "lunch",
    description: "Chicken breast with rice and broccoli",
    cooked: true,
    recipeId: "r2",
    createdAt: today,
  },
  { id: "m3", date: getDateOffset(-1), type: "breakfast", description: "Scrambled eggs with toast", cooked: true, createdAt: today },
  { id: "m4", date: getDateOffset(-1), type: "lunch", description: "Nasi lemak from food court", cooked: false, createdAt: today },
  {
    id: "m5",
    date: getDateOffset(-1),
    type: "dinner",
    description: "Stir-fried chicken with vegetables",
    cooked: true,
    recipeId: "r1",
    createdAt: today,
  },
]

export const sampleRecipes: Recipe[] = [
  {
    id: "r1",
    title: "Quick Chicken Stir Fry",
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    tags: ["Quick", "High Protein", "Meal Prep"],
    rating: 5,
    timesCooked: 5,
    ingredients: [
      { item: "chicken breast", quantity: 400, unit: "g" },
      { item: "mixed vegetables", quantity: 2, unit: "cups" },
      { item: "soy sauce", quantity: 2, unit: "tbsp" },
      { item: "oyster sauce", quantity: 1, unit: "tbsp" },
      { item: "garlic cloves", quantity: 2, unit: "pcs" },
      { item: "oil", quantity: 1, unit: "tbsp" },
    ],
    instructions:
      "1. Cut chicken into bite-sized pieces\n2. Heat oil in wok over high heat\n3. Add garlic and chicken, cook until golden\n4. Add vegetables and sauces\n5. Stir fry for 5 minutes until veggies are tender\n6. Serve with rice",
    nutrition: { calories: 450, protein: 45, carbs: 30, fat: 15 },
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "r2",
    title: "Meal Prep Chicken & Rice Bowl",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    tags: ["Meal Prep", "High Protein", "Bulking"],
    rating: 4,
    timesCooked: 8,
    ingredients: [
      { item: "chicken breast", quantity: 600, unit: "g" },
      { item: "rice", quantity: 2, unit: "cups" },
      { item: "broccoli", quantity: 500, unit: "g" },
      { item: "soy sauce", quantity: 3, unit: "tbsp" },
      { item: "salt and pepper", quantity: 1, unit: "pinch" },
    ],
    instructions:
      "1. Season chicken with salt and pepper\n2. Bake chicken at 200°C for 25 minutes\n3. Cook rice according to package\n4. Steam broccoli\n5. Divide into 4 containers\n6. Drizzle with soy sauce",
    nutrition: { calories: 520, protein: 50, carbs: 55, fat: 8 },
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "r3",
    title: "Air Fryer Salmon",
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    tags: ["Quick", "Air Fryer", "High Protein"],
    rating: 5,
    timesCooked: 3,
    ingredients: [
      { item: "salmon fillets", quantity: 2, unit: "pcs" },
      { item: "olive oil", quantity: 1, unit: "tbsp" },
      { item: "lemon", quantity: 1, unit: "pc" },
      { item: "dill", quantity: 1, unit: "tsp" },
      { item: "salt and pepper", quantity: 1, unit: "pinch" },
    ],
    instructions:
      "1. Pat salmon dry and season\n2. Brush with olive oil\n3. Air fry at 200°C for 12 minutes\n4. Squeeze lemon and sprinkle dill\n5. Serve with vegetables",
    nutrition: { calories: 380, protein: 35, carbs: 2, fat: 25 },
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "r4",
    title: "High Protein Overnight Oats",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    tags: ["Quick", "Meal Prep", "High Protein"],
    rating: 4,
    timesCooked: 12,
    ingredients: [
      { item: "oats", quantity: 0.5, unit: "cup" },
      { item: "milk", quantity: 1, unit: "cup" },
      { item: "protein powder", quantity: 1, unit: "scoop" },
      { item: "chia seeds", quantity: 1, unit: "tbsp" },
      { item: "berries", quantity: 0.5, unit: "cup" },
      { item: "honey", quantity: 1, unit: "tbsp" },
    ],
    instructions:
      "1. Mix oats, milk, protein powder, and chia seeds\n2. Refrigerate overnight\n3. Top with berries and honey in the morning\n4. Enjoy cold",
    nutrition: { calories: 400, protein: 35, carbs: 45, fat: 10 },
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "r5",
    title: "Veggie Egg Scramble",
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    tags: ["Quick", "Vegetarian", "High Protein"],
    rating: 4,
    timesCooked: 6,
    ingredients: [
      { item: "eggs", quantity: 3, unit: "pcs" },
      { item: "bell peppers", quantity: 0.5, unit: "cup" },
      { item: "onion", quantity: 0.25, unit: "cup" },
      { item: "spinach", quantity: 1, unit: "cup" },
      { item: "cheese", quantity: 30, unit: "g" },
      { item: "salt and pepper", quantity: 1, unit: "pinch" },
    ],
    instructions:
      "1. Beat eggs with salt and pepper\n2. Sauté vegetables in pan\n3. Add eggs and scramble\n4. Add cheese and cook until melted\n5. Serve with toast",
    nutrition: { calories: 320, protein: 24, carbs: 12, fat: 20 },
    createdAt: today,
    updatedAt: today,
  },
]

export const sampleShoppingLists: ShoppingList[] = [
  {
    id: "list1",
    store: "Jaya Grocer",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "list2",
    store: "Mr DIY",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "list3",
    store: "Lazada",
    createdAt: today,
    updatedAt: today,
  },
]

export const sampleShoppingItems: ShoppingItem[] = [
  {
    id: "s1",
    listId: "list1",
    item: "Chicken breast",
    quantity: "2kg",
    category: "Protein",
    priority: "need",
    status: "pending",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "s2",
    listId: "list1",
    item: "Rice",
    quantity: "5kg",
    category: "Grains",
    priority: "need",
    status: "pending",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "s3",
    listId: "list1",
    item: "Broccoli",
    quantity: "500g",
    category: "Vegetables",
    priority: "need",
    status: "pending",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "s4",
    listId: "list1",
    item: "Protein powder",
    quantity: "1 tub",
    category: "Supplements",
    priority: "want",
    status: "bought",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "s5",
    listId: "list1",
    item: "Greek yogurt",
    quantity: "4 cups",
    category: "Dairy",
    priority: "want",
    status: "pending",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "s6",
    listId: "list2",
    item: "Storage containers",
    quantity: "10 pack",
    category: "Kitchen",
    priority: "need",
    status: "pending",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "s7",
    listId: "list2",
    item: "Cleaning supplies",
    quantity: "1 set",
    category: "Household",
    priority: "need",
    status: "pending",
    createdAt: today,
    updatedAt: today,
  },
  {
    id: "s8",
    listId: "list3",
    item: "Boxing gloves",
    quantity: "1 pair",
    category: "Fitness",
    priority: "someday",
    status: "pending",
    createdAt: today,
    updatedAt: today,
  },
]

export const RECIPE_TAGS = [
  "Quick",
  "Meal Prep",
  "Air Fryer",
  "Bulking",
  "Cutting",
  "High Protein",
  "Low Carb",
  "Vegetarian",
]

export const STORES = ["Jaya Grocer", "Mr DIY", "Lazada", "Shopee", "Aeon", "Other"]
