import type { Goal, Task, JournalEntry, TrainingSession, Meal, Recipe, ShoppingItem } from "./types"

const today = new Date()
const formatDate = (date: Date) => date.toISOString().split("T")[0]

export const sampleGoals: Goal[] = [
  {
    id: "g1",
    title: "Train Muay Thai 4x per week consistently",
    aspect: "fitness",
    level: "yearly",
    successCriteria: "Complete 200+ training sessions by year end",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progress: 3,
  },
  {
    id: "g2",
    title: "January: Build training habit",
    aspect: "fitness",
    level: "monthly",
    successCriteria: "16 sessions in January",
    startDate: "2026-01-01",
    endDate: "2026-01-31",
    parentId: "g1",
    progress: 12,
  },
  {
    id: "g3",
    title: "Cook 80% of meals at home",
    aspect: "nutrition",
    level: "yearly",
    successCriteria: "Track meals daily and maintain 80% home-cooked ratio",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progress: 15,
  },
  {
    id: "g4",
    title: "Secure senior developer position",
    aspect: "career",
    level: "yearly",
    successCriteria: "Get promoted or land new senior role by Q3",
    startDate: "2026-01-01",
    endDate: "2026-09-30",
    progress: 5,
  },
  {
    id: "g5",
    title: "Build portfolio website",
    aspect: "career",
    level: "monthly",
    successCriteria: "Launch personal portfolio by end of January",
    startDate: "2026-01-01",
    endDate: "2026-01-31",
    parentId: "g4",
    progress: 40,
  },
  {
    id: "g6",
    title: "Save $10,000 emergency fund",
    aspect: "financial",
    level: "yearly",
    successCriteria: "Reach $10,000 in savings account",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progress: 8,
  },
  {
    id: "g7",
    title: "Launch side project MVP",
    aspect: "side-projects",
    level: "yearly",
    successCriteria: "Ship working MVP with 100 users",
    startDate: "2026-01-01",
    endDate: "2026-06-30",
    progress: 20,
  },
  {
    id: "g8",
    title: "Maintain clean living space",
    aspect: "chores",
    level: "yearly",
    successCriteria: "Complete weekly cleaning routine 80% of weeks",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    progress: 25,
  },
]

const getDateOffset = (days: number) => {
  const date = new Date(today)
  date.setDate(date.getDate() + days)
  return formatDate(date)
}

export const sampleTasks: Task[] = [
  {
    id: "t1",
    title: "Morning Muay Thai training",
    aspect: "fitness",
    timePreference: "morning",
    duration: 90,
    status: "pending",
    date: getDateOffset(0),
    goalId: "g1",
    isRecurring: true,
  },
  {
    id: "t2",
    title: "Meal prep for the week",
    aspect: "nutrition",
    timePreference: "afternoon",
    duration: 120,
    status: "pending",
    date: getDateOffset(0),
    goalId: "g3",
    isRecurring: false,
  },
  {
    id: "t3",
    title: "Review job applications",
    aspect: "career",
    timePreference: "evening",
    duration: 30,
    status: "pending",
    date: getDateOffset(0),
    goalId: "g4",
    isRecurring: false,
  },
  {
    id: "t4",
    title: "Update portfolio projects page",
    aspect: "career",
    timePreference: "anytime",
    duration: 60,
    status: "pending",
    date: getDateOffset(0),
    goalId: "g5",
    isRecurring: false,
  },
  {
    id: "t5",
    title: "Budget review",
    aspect: "financial",
    timePreference: "evening",
    duration: 20,
    status: "done",
    date: getDateOffset(-1),
    goalId: "g6",
    isRecurring: false,
  },
  {
    id: "t6",
    title: "Work on side project API",
    aspect: "side-projects",
    timePreference: "evening",
    duration: 90,
    status: "pending",
    date: getDateOffset(1),
    goalId: "g7",
    isRecurring: false,
  },
  {
    id: "t7",
    title: "Vacuum and mop floors",
    aspect: "chores",
    timePreference: "morning",
    duration: 45,
    status: "pending",
    date: getDateOffset(1),
    goalId: "g8",
    isRecurring: true,
  },
  {
    id: "t8",
    title: "Cardio session",
    aspect: "fitness",
    timePreference: "morning",
    duration: 30,
    status: "done",
    date: getDateOffset(-2),
    isRecurring: true,
  },
  {
    id: "t9",
    title: "Plan weekly meals",
    aspect: "nutrition",
    timePreference: "anytime",
    duration: 20,
    status: "done",
    date: getDateOffset(-3),
    goalId: "g3",
    isRecurring: true,
  },
  {
    id: "t10",
    title: "Laundry",
    aspect: "chores",
    timePreference: "afternoon",
    duration: 30,
    status: "skipped",
    date: getDateOffset(-4),
    isRecurring: true,
  },
]

export const sampleJournalEntries: JournalEntry[] = [
  {
    id: "j1",
    date: getDateOffset(0),
    content:
      "Great training session today! Felt strong and focused. Coach complimented my technique. Excited to keep this momentum going.",
    sentiment: "positive",
    aspects: ["fitness"],
    goalAlignment: ["g1"],
  },
  {
    id: "j2",
    date: getDateOffset(-1),
    content:
      "Had a tough day at work. The project deadline is stressing me out. Need to organize my time better and maybe ask for help.",
    sentiment: "negative",
    aspects: ["career"],
    goalAlignment: ["g4"],
  },
  {
    id: "j3",
    date: getDateOffset(-2),
    content:
      "Cooked a new recipe today - chicken stir fry with lots of veggies. Turned out amazing! Meal prepping is really paying off.",
    sentiment: "positive",
    aspects: ["nutrition"],
    goalAlignment: ["g3"],
  },
  {
    id: "j4",
    date: getDateOffset(-5),
    content:
      "Made good progress on the side project this weekend. The authentication flow is finally working. Feels good to ship features.",
    sentiment: "positive",
    aspects: ["side-projects"],
    goalAlignment: ["g7"],
  },
  {
    id: "j5",
    date: getDateOffset(-7),
    content:
      "Feeling a bit burnt out. Juggling work, training, and side projects is exhausting. Maybe I need to cut back somewhere.",
    sentiment: "neutral",
    aspects: ["fitness", "career", "side-projects"],
    goalAlignment: ["g1", "g4", "g7"],
  },
]

export const sampleTrainingSessions: TrainingSession[] = [
  {
    id: "ts1",
    date: getDateOffset(0),
    type: "muay-thai",
    duration: 90,
    intensity: 8,
    notes: "Sparring day - good rounds",
  },
  { id: "ts2", date: getDateOffset(-2), type: "muay-thai", duration: 90, intensity: 7 },
  { id: "ts3", date: getDateOffset(-3), type: "cardio", duration: 30, intensity: 6, notes: "Morning run" },
  { id: "ts4", date: getDateOffset(-5), type: "muay-thai", duration: 90, intensity: 9, notes: "Pad work with coach" },
  { id: "ts5", date: getDateOffset(-7), type: "strength", duration: 60, intensity: 7, notes: "Upper body day" },
  { id: "ts6", date: getDateOffset(-9), type: "muay-thai", duration: 90, intensity: 8 },
  { id: "ts7", date: getDateOffset(-10), type: "flexibility", duration: 45, intensity: 5, notes: "Yoga session" },
  { id: "ts8", date: getDateOffset(-12), type: "muay-thai", duration: 90, intensity: 8 },
]

export const sampleMeals: Meal[] = [
  {
    id: "m1",
    date: getDateOffset(0),
    type: "breakfast",
    description: "Oatmeal with berries and protein powder",
    cooked: true,
  },
  {
    id: "m2",
    date: getDateOffset(0),
    type: "lunch",
    description: "Chicken breast with rice and broccoli",
    cooked: true,
    recipeId: "r2",
  },
  { id: "m3", date: getDateOffset(-1), type: "breakfast", description: "Scrambled eggs with toast", cooked: true },
  { id: "m4", date: getDateOffset(-1), type: "lunch", description: "Nasi lemak from food court", cooked: false },
  {
    id: "m5",
    date: getDateOffset(-1),
    type: "dinner",
    description: "Stir-fried chicken with vegetables",
    cooked: true,
    recipeId: "r1",
  },
]

export const sampleRecipes: Recipe[] = [
  {
    id: "r1",
    title: "Quick Chicken Stir Fry",
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    tags: ["Quick", "High Protein", "Meal Prep"],
    rating: 5,
    ingredients: [
      "400g chicken breast",
      "2 cups mixed vegetables",
      "2 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "2 cloves garlic",
      "1 tbsp oil",
    ],
    instructions:
      "1. Cut chicken into bite-sized pieces\n2. Heat oil in wok over high heat\n3. Add garlic and chicken, cook until golden\n4. Add vegetables and sauces\n5. Stir fry for 5 minutes until veggies are tender\n6. Serve with rice",
    nutrition: "450 calories, 45g protein, 30g carbs, 15g fat",
  },
  {
    id: "r2",
    title: "Meal Prep Chicken & Rice Bowl",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    tags: ["Meal Prep", "High Protein", "Bulking"],
    rating: 4,
    ingredients: ["600g chicken breast", "2 cups rice", "500g broccoli", "3 tbsp soy sauce", "Salt and pepper"],
    instructions:
      "1. Season chicken with salt and pepper\n2. Bake chicken at 200°C for 25 minutes\n3. Cook rice according to package\n4. Steam broccoli\n5. Divide into 4 containers\n6. Drizzle with soy sauce",
    nutrition: "520 calories, 50g protein, 55g carbs, 8g fat",
  },
  {
    id: "r3",
    title: "Air Fryer Salmon",
    prepTime: 5,
    cookTime: 12,
    servings: 2,
    tags: ["Quick", "Air Fryer", "High Protein"],
    rating: 5,
    ingredients: ["2 salmon fillets", "1 tbsp olive oil", "1 lemon", "Dill", "Salt and pepper"],
    instructions:
      "1. Pat salmon dry and season\n2. Brush with olive oil\n3. Air fry at 200°C for 12 minutes\n4. Squeeze lemon and sprinkle dill\n5. Serve with vegetables",
    nutrition: "380 calories, 35g protein, 2g carbs, 25g fat",
  },
  {
    id: "r4",
    title: "High Protein Overnight Oats",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    tags: ["Quick", "Meal Prep", "High Protein"],
    rating: 4,
    ingredients: ["1/2 cup oats", "1 cup milk", "1 scoop protein powder", "1 tbsp chia seeds", "Berries", "Honey"],
    instructions:
      "1. Mix oats, milk, protein powder, and chia seeds\n2. Refrigerate overnight\n3. Top with berries and honey in the morning\n4. Enjoy cold",
    nutrition: "400 calories, 35g protein, 45g carbs, 10g fat",
  },
  {
    id: "r5",
    title: "Veggie Egg Scramble",
    prepTime: 5,
    cookTime: 8,
    servings: 1,
    tags: ["Quick", "Vegetarian", "High Protein"],
    rating: 4,
    ingredients: ["3 eggs", "Bell peppers", "Onion", "Spinach", "Cheese", "Salt and pepper"],
    instructions:
      "1. Beat eggs with salt and pepper\n2. Sauté vegetables in pan\n3. Add eggs and scramble\n4. Add cheese and cook until melted\n5. Serve with toast",
    nutrition: "320 calories, 24g protein, 12g carbs, 20g fat",
  },
]

export const sampleShoppingItems: ShoppingItem[] = [
  {
    id: "s1",
    store: "Jaya Grocer",
    name: "Chicken breast",
    quantity: "2kg",
    category: "Protein",
    priority: "need",
    bought: false,
  },
  {
    id: "s2",
    store: "Jaya Grocer",
    name: "Rice",
    quantity: "5kg",
    category: "Grains",
    priority: "need",
    bought: false,
  },
  {
    id: "s3",
    store: "Jaya Grocer",
    name: "Broccoli",
    quantity: "500g",
    category: "Vegetables",
    priority: "need",
    bought: false,
  },
  {
    id: "s4",
    store: "Jaya Grocer",
    name: "Protein powder",
    quantity: "1 tub",
    category: "Supplements",
    priority: "want",
    bought: true,
  },
  {
    id: "s5",
    store: "Jaya Grocer",
    name: "Greek yogurt",
    quantity: "4 cups",
    category: "Dairy",
    priority: "want",
    bought: false,
  },
  {
    id: "s6",
    store: "Mr DIY",
    name: "Storage containers",
    quantity: "10 pack",
    category: "Kitchen",
    priority: "need",
    bought: false,
  },
  {
    id: "s7",
    store: "Mr DIY",
    name: "Cleaning supplies",
    quantity: "1 set",
    category: "Household",
    priority: "need",
    bought: false,
  },
  {
    id: "s8",
    store: "Lazada",
    name: "Boxing gloves",
    quantity: "1 pair",
    category: "Fitness",
    priority: "someday",
    bought: false,
  },
]

export const RECIPE_TAGS = [
  "Quick",
  "Meal Prep",
  "Air Fryer",
  "Bulking",
  "Cutting",
  "High Protein",
  "Low Carb",
  "Vegetarian",
]

export const STORES = ["Jaya Grocer", "Mr DIY", "Lazada", "Shopee", "Aeon", "Other"]
